# 均以 http://uoj.ac/contest/1 为例

# 比赛链接，即从比赛页面点进去的第一个页面
contest_url: http://uoj.ac/contest/1

# 爬取的分数下限，即大于等于这个分数的提交才会被爬取
least_score: 100

# 搜索关键字，请按照题号的顺序给出。如果有更多题目可手动添加。如果没有则以题目标题为关键字搜索
keywords:
  - LOJ10002
  - LOJ10009
  - POJ2054

# 搜索页数，越多越精确，但耗时更多
pages: 2

# 相似度阀值，即相似度超过这个百分比就会输出到result.txt中
sim_limit: 10

# 使用搜索引擎设置，百度为baidu，必应为bing，谷歌为google(谷歌暂不支持)
site: baidu

# 浏览器useragent，若没有特殊情况可以保持默认
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0