# 搜索关键字，建议粘贴题目中的一段文字或准确题号
keyword: Mayan puzzle是最近流行起来的一个游戏。游戏界面是一个7 行×5 

# 百度搜索页数，越多越精确，但耗时更多
baidu_pages: 3

# 相似度阀值，即相似度超过这个百分比就会输出到result.txt中
sim_limit: 10

# 浏览器useragent，若没有特殊情况可以保持默认
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

# 使用搜索引擎设置，百度为baidu，必应为bing，谷歌为google
site: baidu