# 全局设置

# 使用模式，可选 1 或 2 ，功能请见 README.md
mode: 2

# UserAgent，改不改无所谓
ua: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

# 搜索引擎，可选 baidu ，未来会有更多支持
site: baidu

# 搜索页数，越多越精确，但耗时更多
pages: 1

# 最长等待时间，建议0.5以上，否则可能会大范围跳过
time_out: 1

# 相似度阀值，即相似度超过这个百分比就会输出到result.txt中
sim_limit: 0

#----------分----------隔----------线----------

# V1 ，如果使用V1模式在这里设置

# 需要比对的文件位置，请使用完整地址
local: a.cpp

#----------分----------隔----------线----------

# V2 ，如果使用V2模式在这里设置

# OJ ，暂时只支持基于UOJ搭建的OJ，以 http://uoj.ac/contest/1 为例
oj: uoj

# 基于OJ地址，不要带上最后的'/'
oj_url: http://uoj.ac

# 比赛编号
contest_id: 1

# 爬取的分数下限，即大于等于这个分数的提交才会被爬取（暂时不支持修改）
least_score: 100

# 比赛中题号，请按照比赛题目顺序给出。如果有更多题目可手动添加。
problems:
  - 9
  - 10
  - 11

# 搜索关键字，请按照题号的顺序给出。
keywords:
  - UOJ上，由于一群人开心的在hack着，有的题的测试数据都有1000010000组了！
  - pyx喜欢出题给cyb做。为了增加难度，他有可能在cyb还没做完前面的题的时候就把新题目出给他。
  - ydc有一棵nn个结点的黑白相间的大树，从11到nn编号。