# 均以 http://uoj.ac/contest/1 为例

# 基于UOJ的OJ地址，不要带上最后的'/'
oj_url: http://172.16.49.190

# 比赛编号
contest_id: 10

# 爬取的分数下限，即大于等于这个分数的提交才会被爬取
least_score: 100

# 比赛中题号，请按照比赛题目顺序给出。如果有更多题目可手动添加。
problems:
  - 19
  - 20
  - 21

# 搜索关键字，请按照题号的顺序给出。
keywords:
  - LOJ10002
  - LOJ10009
  - POJ2054

# 搜索页数，越多越精确，但耗时更多
pages: 2

# 相似度阀值，即相似度超过这个百分比就会输出到result.txt中
sim_limit: 10